FW-5026 ADD optimize cypress tests
First-Peoples-Cultural-Council/fv-web pull request #182
Opened 2023-10-31 21:00 UTC by chrisfpcc

### Description of Changes

Add cypress tests and main core suite test

### Checklist

- [ ] README / documentation has been updated if needed
- [x] PR title / commit messages contain Jira ticket number if applicable
- [x] Tests have been updated / created if applicable

### Reviewers Should Do The Following:

- [x] Review the changes here
- [ ] Pull the branch and test locally

### Additional Notes

N/A

2023-11-01 17:24 UTC, NolanVH requested changes
Thanks for the large update to many of the Cypress tests @chrisfpcc!

These changes are looking great but there are a few issues I have spotted.

One of the bigger things is that some of the tests are still pointing at Nuxeo endpoints which should be removed. It also looks like the cypress.config file has the base URL hardcoded and pointing at the pre-prod site running the old Nuxeo backend. I was not able to run the tests pointed at my local environment without several code changes because of this.

The other thing that would be useful for others is some setup instructions in the README explaining what environment variables need to be set, what commands run the tests, etc. This could be done as a separate ticket.

2023-11-01 17:24 UTC, NolanVH commented on cypress/e2e/core_suite_master.cy.js
> +    cy.contains('QR CODE').click()
Adding the second `.contains` for clicking is redundant in this block. 
Eg this: 
```
cy.contains('MORE')
cy.contains('MORE').click()
```
could be simplified to this:
```
cy.contains('MORE').click()
```

2023-11-01 17:24 UTC, NolanVH commented on cypress/e2e/core_suite_master.cy.js
This file is very large and contains an assortment of different tests. It should probably be split up into individual files organized by the component or area of the site being tested.

2023-11-03 21:11 UTC, chrisfpcc commented on cypress/e2e/dashboard/alpha.cy.js
this has been taken care of, removed

2023-11-03 21:11 UTC, chrisfpcc commented on cypress/e2e/dashboard/create_page.cy.js
> +    // it('View Create Page - check vaidation', () => {
removed commented out areas

2023-11-03 21:12 UTC, chrisfpcc commented on cypress/e2e/dashboard/wordup.cy.js
> +    ':nth-child(6) > .mt-2 > .space-y-2 > li > .justify-between > .w-full',
will make jira's to get devs to add in id's, name's

2023-11-03 21:12 UTC, chrisfpcc commented on cypress/e2e/dashboard/pages.cy.js
> -      'Contact Us',
good to know

2023-11-03 21:13 UTC, chrisfpcc commented on cypress/e2e/core_suite_master.cy.js
> +  cy.visit(`${Cypress.env('baseUrl')}`)
will make a jira for it to be done in the future

2023-11-03 21:13 UTC, chrisfpcc commented on cypress/e2e/core_suite_master.cy.js
> +    //   .trigger('mouseup', { force: true, which: 1 })
will be removed once this solution is fixed

2024-01-05 21:42 UTC, NolanVH approved these changes
Some great changes here! Thanks @chrisfpcc! 

Would be great to get some documentation added to the README on how to run these tests locally (what environment variables need to be set, commands to run, etc) so that devs can run these tests before pushing changes, but that can be added in a future PR.

2024-01-08 17:53 UTC, sahil97 approved these changes
Looks good and +1 for Nolan's comment related to documentation.
Nice work @chrisfpcc

2024-01-09 17:21 UTC, merged